drop table member;

create table member (
	MEMBER_ID			VARCHAR2(12) primary key,
	MEMBER_NAME			VARCHAR2(15) NOT NULL,
	MEMBER_PASS			VARCHAR2(12) NOT NULL,
	MEMBER_BIRTH		VARCHAR2(10) NOT NULL,
	MEMBER_EMAIL		VARCHAR2(20) NOT NULL,
	MEMBER_GENDER		NUMBER(2)	 NOT NULL,
	MEMBER_TEL			NUMBER(11)	 NOT NULL,
	MEMBER_ADDRESS		VARCHAR2(30) NOT NULL,
	MEMBER_INTEREST		VARCHAR2(2),
	MEMBER_ACCOUNT		NUMBER(30),
	MEMBER_BANK			VARCHAR2(12),
	MEMBER_FILE			VARCHAR2(50)
);

select * from member;